name: first

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "User"
      environment:
        description: "Select environment"
        required: true
        default: "dev"

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello ${{ github.event.inputs.name }}"

      - name: Print environment
        run: echo "Running in ${{ github.event.inputs.environment }} environment"

      - name: Print testing
        run: echo "tested"
